Wr/timeout message
salesforcecli/plugin-data pull request #967
Opened 2024-06-18 19:24 UTC by WillieRuemmele

### What does this PR do?
refactors similar util files into one
refactors similar types files into one

catches a timeout error so that the timeout event listener can properly handle, and print instructions

### What issues does this PR fix or reference?
@W-16010988@

2024-06-18 19:33 UTC, WillieRuemmele commented on src/bulkOperationBase.ts
> +    try {
catching this error, fixes the bug

2024-06-18 20:14 UTC, jshackell-sfdc requested changes
see my suggestions

2024-06-19 19:54 UTC, mdonnalley approved these changes

2024-06-19 19:55 UTC, mdonnalley commented
QA: Willie and decided offline that the NUTs are sufficient QA for this PR.

2024-06-19 19:56 UTC, merged